utilx.shape: class

# utilx
alogx.shape: class
utilx -> alogx

## algox
searchx.shape: text
alogx -> searchx
sortx.shape: text
alogx -> sortx

# utilx
cmdx.shape: text
utilx -> cmdx

## cmdx
autotidy.shape: text
cmdx -> autotidy
autoupdate.shape: text
cmdx -> autoupdate

# utilx
cryptox.shape: class
utilx -> cryptox

## cryptox
aesx.shape: text
cryptox -> aesx
bcryptx.shape: text
cryptox -> bcryptx
hmacx.shape: text
cryptox -> hmacx
passhashx.shape: text
cryptox -> passhashx
shax.shape: text
cryptox -> shax

# utilx
debugx.shape: class
utilx -> debugx

## debugx
errorx.shape: text
debugx -> errorx
safex.shape: text
debugx -> safex

# utilx
dsx.shape: text
utilx -> dsx

## dsx
arrayx.shape: class
dsx -> arrayx

### arrayx
ringx.shape: text
arrayx -> ringx
stackx.shape: text
arrayx -> stackx

## dsx
listx.shape: class
dsx -> listx

### listx
queuex.shape: text
listx -> queuex
dequex.shape: text
listx -> dequex

## dsx
mapx.shape: class
dsx -> mapx

### mapx
ordmapx.shape: text
mapx -> ordmapx
sklmapx.shape: text
mapx -> sklmapx
syncmapx.shape: text
mapx -> syncmapx

## dsx
treex.shape: class
dsx -> treex

### treex
treemapx.shape: text
treex -> treemapx
btreex.shape: text
treex -> btreex
rbtreex.shape: text
treex -> rbtreex

# utilx
encodex.shape: class
utilx -> encodex

## encodex
gobx.shape: text
encodex -> gobx
jsonx.shape: text
encodex -> jsonx

# utilx
iox.shape: class
utilx -> iox

## iox
usingx.shape: text
iox -> usingx

# utilx
logx.shape: class
utilx -> logx

# utilx
nilx.shape: class
utilx -> nilx

## nilx
optionx.shape: text
nilx -> optionx
resultx.shape: text
nilx -> resultx

# utilx
osx.shape: class
utilx -> osx

# utilx
timex.shape: class
utilx -> timex

## timex
intersectionx.shape: text
timex -> intersectionx
sleepx.shape: text
timex -> sleepx
truncatex.shape: text
timex -> truncatex
