package convx

func init() {
	Register(integerToInteger[int8, int8])
	Register(integerToInteger[int8, int16])
	Register(integerToInteger[int8, int32])
	Register(integerToInteger[int8, int64])
	Register(integerToInteger[int8, int])
	Register(integerToInteger[int8, uint8])
	Register(integerToInteger[int8, uint16])
	Register(integerToInteger[int8, uint32])
	Register(integerToInteger[int8, uint64])
	Register(integerToInteger[int8, uint])
	Register(integerToInteger[int8, float32])
	Register(integerToInteger[int8, float64])
	Register(integerToInteger[int16, int8])
	Register(integerToInteger[int16, int16])
	Register(integerToInteger[int16, int32])
	Register(integerToInteger[int16, int64])
	Register(integerToInteger[int16, int])
	Register(integerToInteger[int16, uint8])
	Register(integerToInteger[int16, uint16])
	Register(integerToInteger[int16, uint32])
	Register(integerToInteger[int16, uint64])
	Register(integerToInteger[int16, uint])
	Register(integerToInteger[int16, float32])
	Register(integerToInteger[int16, float64])
	Register(integerToInteger[int32, int8])
	Register(integerToInteger[int32, int16])
	Register(integerToInteger[int32, int32])
	Register(integerToInteger[int32, int64])
	Register(integerToInteger[int32, int])
	Register(integerToInteger[int32, uint8])
	Register(integerToInteger[int32, uint16])
	Register(integerToInteger[int32, uint32])
	Register(integerToInteger[int32, uint64])
	Register(integerToInteger[int32, uint])
	Register(integerToInteger[int32, float32])
	Register(integerToInteger[int32, float64])
	Register(integerToInteger[int64, int8])
	Register(integerToInteger[int64, int16])
	Register(integerToInteger[int64, int32])
	Register(integerToInteger[int64, int64])
	Register(integerToInteger[int64, int])
	Register(integerToInteger[int64, uint8])
	Register(integerToInteger[int64, uint16])
	Register(integerToInteger[int64, uint32])
	Register(integerToInteger[int64, uint64])
	Register(integerToInteger[int64, uint])
	Register(integerToInteger[int64, float32])
	Register(integerToInteger[int64, float64])
	Register(integerToInteger[int, int8])
	Register(integerToInteger[int, int16])
	Register(integerToInteger[int, int32])
	Register(integerToInteger[int, int64])
	Register(integerToInteger[int, int])
	Register(integerToInteger[int, uint8])
	Register(integerToInteger[int, uint16])
	Register(integerToInteger[int, uint32])
	Register(integerToInteger[int, uint64])
	Register(integerToInteger[int, uint])
	Register(integerToInteger[int, float32])
	Register(integerToInteger[int, float64])
	Register(integerToInteger[uint8, int8])
	Register(integerToInteger[uint8, int16])
	Register(integerToInteger[uint8, int32])
	Register(integerToInteger[uint8, int64])
	Register(integerToInteger[uint8, int])
	Register(integerToInteger[uint8, uint8])
	Register(integerToInteger[uint8, uint16])
	Register(integerToInteger[uint8, uint32])
	Register(integerToInteger[uint8, uint64])
	Register(integerToInteger[uint8, uint])
	Register(integerToInteger[uint8, float32])
	Register(integerToInteger[uint8, float64])
	Register(integerToInteger[uint16, int8])
	Register(integerToInteger[uint16, int16])
	Register(integerToInteger[uint16, int32])
	Register(integerToInteger[uint16, int64])
	Register(integerToInteger[uint16, int])
	Register(integerToInteger[uint16, uint8])
	Register(integerToInteger[uint16, uint16])
	Register(integerToInteger[uint16, uint32])
	Register(integerToInteger[uint16, uint64])
	Register(integerToInteger[uint16, uint])
	Register(integerToInteger[uint16, float32])
	Register(integerToInteger[uint16, float64])
	Register(integerToInteger[uint32, int8])
	Register(integerToInteger[uint32, int16])
	Register(integerToInteger[uint32, int32])
	Register(integerToInteger[uint32, int64])
	Register(integerToInteger[uint32, int])
	Register(integerToInteger[uint32, uint8])
	Register(integerToInteger[uint32, uint16])
	Register(integerToInteger[uint32, uint32])
	Register(integerToInteger[uint32, uint64])
	Register(integerToInteger[uint32, uint])
	Register(integerToInteger[uint32, float32])
	Register(integerToInteger[uint32, float64])
	Register(integerToInteger[uint64, int8])
	Register(integerToInteger[uint64, int16])
	Register(integerToInteger[uint64, int32])
	Register(integerToInteger[uint64, int64])
	Register(integerToInteger[uint64, int])
	Register(integerToInteger[uint64, uint8])
	Register(integerToInteger[uint64, uint16])
	Register(integerToInteger[uint64, uint32])
	Register(integerToInteger[uint64, uint64])
	Register(integerToInteger[uint64, uint])
	Register(integerToInteger[uint64, float32])
	Register(integerToInteger[uint64, float64])
	Register(integerToInteger[uint, int8])
	Register(integerToInteger[uint, int16])
	Register(integerToInteger[uint, int32])
	Register(integerToInteger[uint, int64])
	Register(integerToInteger[uint, int])
	Register(integerToInteger[uint, uint8])
	Register(integerToInteger[uint, uint16])
	Register(integerToInteger[uint, uint32])
	Register(integerToInteger[uint, uint64])
	Register(integerToInteger[uint, uint])
	Register(integerToInteger[uint, float32])
	Register(integerToInteger[uint, float64])
	Register(integerToInteger[float32, int8])
	Register(integerToInteger[float32, int16])
	Register(integerToInteger[float32, int32])
	Register(integerToInteger[float32, int64])
	Register(integerToInteger[float32, int])
	Register(integerToInteger[float32, uint8])
	Register(integerToInteger[float32, uint16])
	Register(integerToInteger[float32, uint32])
	Register(integerToInteger[float32, uint64])
	Register(integerToInteger[float32, uint])
	Register(integerToInteger[float32, float32])
	Register(integerToInteger[float32, float64])
	Register(integerToInteger[float64, int8])
	Register(integerToInteger[float64, int16])
	Register(integerToInteger[float64, int32])
	Register(integerToInteger[float64, int64])
	Register(integerToInteger[float64, int])
	Register(integerToInteger[float64, uint8])
	Register(integerToInteger[float64, uint16])
	Register(integerToInteger[float64, uint32])
	Register(integerToInteger[float64, uint64])
	Register(integerToInteger[float64, uint])
	Register(integerToInteger[float64, float32])
	Register(integerToInteger[float64, float64])
	Register(stringToInteger[int8])
	Register(stringToInteger[int16])
	Register(stringToInteger[int32])
	Register(stringToInteger[int64])
	Register(stringToInteger[int])
	Register(stringToUinteger[uint8])
	Register(stringToUinteger[uint16])
	Register(stringToUinteger[uint32])
	Register(stringToUinteger[uint64])
	Register(stringToUinteger[uint])
	Register(stringToFloat[float32])
	Register(stringToFloat[float64])
	Register(intToString[int8])
	Register(intToString[int16])
	Register(intToString[int32])
	Register(intToString[int64])
	Register(intToString[int])
	Register(uintToString[uint8])
	Register(uintToString[uint16])
	Register(uintToString[uint32])
	Register(uintToString[uint64])
	Register(uintToString[uint])
	Register(floatToString[float32])
	Register(floatToString[float64])
	Register(boolToInteger[int8])
	Register(boolToInteger[int16])
	Register(boolToInteger[int32])
	Register(boolToInteger[int64])
	Register(boolToInteger[int])
	Register(boolToInteger[uint8])
	Register(boolToInteger[uint16])
	Register(boolToInteger[uint32])
	Register(boolToInteger[uint64])
	Register(boolToInteger[uint])
	Register(boolToFloat[float32])
	Register(boolToFloat[float64])
	Register(boolToString)
	Register(intToBool[int8])
	Register(intToBool[int16])
	Register(intToBool[int32])
	Register(intToBool[int64])
	Register(intToBool[int])
	Register(intToBool[uint8])
	Register(intToBool[uint16])
	Register(intToBool[uint32])
	Register(intToBool[uint64])
	Register(intToBool[uint])
	Register(floatToBool[float32])
	Register(floatToBool[float64])
	Register(stringToBool)
	Register(stringToString)
	Register(boolToBool)
	Register(stringToBytes)
	Register(bytesToString)
	Register(bytesToBytes)
	Register(stringToRunes)
	Register(runesToString)
	Register(runesToRunes)
}
