# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [
          ./algox,
          ./algox/searchx,
          ./algox/sortx,
          ./cryptox,
          ./cryptox/aesx,
          ./cryptox/bcryptx,
          ./cryptox/hmacx,
          ./cryptox/passhashx,
          ./cryptox/shax,
          ./debugx,
          ./debugx/errorx,
          ./debugx/safex,
          ./dsx,
          ./dsx/dequex,
          ./dsx/listx,
          ./dsx/mapx,
          ./dsx/mapx/ordmapx,
          ./dsx/mapx/syncmapx,
          ./dsx/mapx/treemapx,
          ./dsx/queuex,
          ./dsx/ringx,
          ./dsx/stackx,
          ./dsx/treex,
          ./dsx/treex/btreex,
          ./dsx/treex/rbtreex,
          ./encodex,
          ./encodex/gobx,
          ./encodex/jsonx,
          ./iox,
          ./iox/usingx,
          ./logx,
          ./nilx,
          ./nilx/optionx,
          ./nilx/resultx,
          ./osx,
          ./timex,
          ./timex/intersectionx,
          ./timex/sleepx,
          ./timex/truncatex,
        ]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ${{ matrix.package }}/...

    - name: Test
      run: go test -v ${{ matrix.package }}/...
